#	FILE			: makefile
#	PROJECT			: SP_A03
#	PROGRAMMER		: Mita Das & Colby Taylor
#	FIRST VERSION		: 2022-02-21
#	DESCRIPTION		: this makefile will compile the other makefiles
#
# 
#
#
#
#
######## Call the common make
cd Common
make clean
make
cd ..
#
#
#
######## Call the data reader make
cd DataReader
make clean
make
cd ..
#
#
#
######## Call the data creator make
cd DataCreator
make clean
make
cd ..
#
#
#
######## Call the data corruptor make
cd DataCorruptor
make clean
make
cd ..

